version: '3.9'

services:
  wiremock:
    image: wiremock/wiremock:latest
    restart: on-failure:3
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/stubs:/home/wiremock

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: ["sh", "-c", "python src/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - wiremock
    environment:
      - DB_HOST=db
      - DB_NAME=sqs
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
      - API_BASE_URL=http://wiremock:8080/api/v1/
      - API_KEY=API_KEY
      - TOKEN_UNIT_TEST=dcd52b4996698b6c5db63df6894550fe1069d2a0
      - SECRET_KEY=yoursupersecuresecretkey
      - DJANGO_SUPERUSER_PASSWORD=thatsmysecretpw123!

  db:
    image: mysql:latest
    restart: on-failure:3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: sqs
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
