version: '3.9'

services:
  web:
    build:
      dockerfile: src/Dockerfile
    command: ["sh", "-c", "python src/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
