version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: ["sh", "-c", "python src/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sqs
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306

  db:
    image: mysql:latest
    restart: on-failure:3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: sqs
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
