# Generated by Django 5.0.6 on 2024-06-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbonscore', '0001_create_requests_table'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE carbon_score (
                id INT AUTO_INCREMENT PRIMARY KEY,
                carbon_g DECIMAL(10,2) NOT NULL,
                carbon_kg DECIMAL(10,2) NOT NULL,
                carbon_lb DECIMAL(10,2) NOT NULL,
                carbon_mt DECIMAL(10,2) NOT NULL,
                session_id VARCHAR(255) NOT NULL
            );
            """,
            reverse_sql="DROP TABLE request;"
        ),
    ]
