# Generated by Django 5.0.6 on 2024-06-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE request (
                id INT AUTO_INCREMENT PRIMARY KEY,
                request VARCHAR(500) NOT NULL,
                session_id VARCHAR(255) NOT NULL
            );
            """,
            reverse_sql="DROP TABLE request;"
        ),
    ]
