name: Django CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: start virtual environment
      run: |
        cd src/.venv
        source tutorial-env/bin/activate 
    - name: env
      run: |
        echo "SECRET_KEY=topsecretvalue" >> $GITHUB_ENV
        echo "TOKEN_UNIT_TEST=ae7c53dcaafe8887d331003252fa90f6c5ff5059" >> $GITHUB_ENV
        echo "API_BASE_URL=https://carbon-score.wiremockapi.cloud/api/v1/" >> $GITHUB_ENV
        echo "API_KEY=API_KEY" >> $GITHUB_ENV
    - name: Run Tests
      run: |
        cd src
        coverage run manage.py test
        coverage xml -o coverage-reports/coverage.xml
    - name: Run ArchUnit with Import-linter
      run: |
        cd src
        lint-imports
    - name: Run Wiremock Tests
      run: |
        cd src/application
        python -m pytest restassured_tests.py
    - name: locust load test
      run: |
        cd src
        python manage.py runserver
        cd application
        locust -H http://127.0.0.1:8000/ -f locustfile.py -u 50 -t 2m --autostart --autoquit 0 --html locust_report.html  
