name: Django CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up virtual environment
      run: |
        python -m venv src/.venv
        source src/.venv/bin/activate
    - name: env
      run: |
        echo "SECRET_KEY=topsecretvalue" >> $GITHUB_ENV
        echo "TOKEN_UNIT_TEST=ae7c53dcaafe8887d331003252fa90f6c5ff5059" >> $GITHUB_ENV
        echo "API_BASE_URL=https://carbon-score.wiremockapi.cloud/api/v1/" >> $GITHUB_ENV
        echo "API_KEY=API_KEY" >> $GITHUB_ENV
        echo "DEBUG=TRUE" >> $GITHUB_ENV
    - name: Run Tests
      run: |
        cd src
        source .venv/bin/activate
        coverage run manage.py test
        coverage xml -o coverage-reports/coverage.xml

    - name: Edit coverage report
      run: |
        sed -i 's|<source>/home/runner/work/sqs-application/sqs-application/src</source>|<source>/usr/src/</source>|g' src/coverage-reports/coverage.xml

    - name: Commit coverage report
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/coverage-reports/coverage.xml
        git commit -m 'Add coverage report'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Run ArchUnit with Import-linter
      run: |
        cd src
        source .venv/bin/activate
        lint-imports

    # WireMock über Cloud Service verfügbar
    # - name: Run Wiremock Tests
    #  run: |
    #    cd src/application
    #    source ../.venv/bin/activate
    #    python -m pytest restassured_tests.py
