name: Docker build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for MySQL
      run: |
        sudo apt-get install -y mysql-client
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 1
        done

    - name: List containers
      run: docker ps

    - name: Check directory structure
      run: docker-compose exec -T web ls -l src

    - name: Run migrations
      run: |
        CONTAINER_ID=$(docker ps -qf "name=sqs-application_web_1")
        docker exec -T $CONTAINER_ID sh -c "cd src && python manage.py migrate"
  
    - name: Run migrations and tests
      run: |
          CONTAINER_ID=$(docker ps -qf "name=sqs-application_web_1")
          docker exec $CONTAINER_ID sh -c "cd src && python manage.py test --verbosity=2"

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down
