name: Load Testing

on:
    workflow_run:
      workflows: ["Django CI"]
      types:
        - completed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run Locust load test
              run: locust -f locustfile.py --headless -u 100 -r 10 --run-time 15s
